version: "3.9"

services:
  web:
    build: .
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "./db:/code/db"

